version: "3.4"

# Development environment override
services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - target: 3306
        published: 3307
        protocol: tcp
###< doctrine/doctrine-bundle ###

  php:
    volumes:
      - ./:/srv/app:rw,cached
      - ./docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
      # If you develop on Linux, comment out the following volumes to just use bind-mounted project directory from host
      # - ./var:/srv/app/var:rw
    environment:
      APP_ENV: dev

  caddy:
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/srv/app/public:ro
    ports:
      # HTTP
      - target: 80
        published: 801
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
      # HTTP/3
      - target: 443
        published: 443
        protocol: udp
